version: '3.4'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}